### PR TITLE
Extract launchpad

### PR DESCRIPTION
**Pull request by un-tone**
For https://github.com/StarcounterApps/Launcher/issues/267

### CODE REVIEW

**Comment by warpech** [comment]
This an excellent piece of work. I must say that I was actually not considering to remove launchpad from Launcher, but just add is as a separate app. But now that you have made the effort to remove launchpad from Launcher, I think that we should accept this PR after https://github.com/StarcounterApps/Launchpad/pull/1 gets released.

@tomalec do you agree?

**Comment by tomalec** [comment]
Definitely!
I always like to see su much code removed :)

**Comment by warpech** [comment]
I think it can be merged only after Website, Launchpad are released and after it is confirmed that Settings pages still work without Launcher.

**Comment by warpech** [comment]
Similarly to the reason why https://github.com/StarcounterApps/Launcher/pull/290 was closed, I will close this PR too. We are moving towards splitting Launcher into separate apps so that we no longer have to maintain Launcher. Merging of this PR is not needed then.

Thanks for your great work @un-tone!

**Pull request closed without merging**
